config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'

  resources :cadernos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caderno.rb
class Caderno < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cadernos_controller.rb
class CadernosController < ApplicationController
  before_action :set_caderno, only: [:show, :edit, :update, :destroy]

  # GET /cadernos
  # GET /cadernos.json
  def index
    @cadernos = Caderno.all
  end

  # GET /cadernos/1
  # GET /cadernos/1.json
  def show
  end

  # GET /cadernos/new
  def new
    @caderno = Caderno.new
  end

  # GET /cadernos/1/edit
  def edit
  end

  # POST /cadernos
  # POST /cadernos.json
  def create
    @caderno = Caderno.new(caderno_params)

    respond_to do |format|
      if @caderno.save
        format.html { redirect_to @caderno, notice: 'Caderno was successfully created.' }
        format.json { render :show, status: :created, location: @caderno }
      else
        format.html { render :new }
        format.json { render json: @caderno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadernos/1
  # PATCH/PUT /cadernos/1.json
  def update
    respond_to do |format|
      if @caderno.update(caderno_params)
        format.html { redirect_to @caderno, notice: 'Caderno was successfully updated.' }
        format.json { render :show, status: :ok, location: @caderno }
      else
        format.html { render :edit }
        format.json { render json: @caderno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadernos/1
  # DELETE /cadernos/1.json
  def destroy
    @caderno.destroy
    respond_to do |format|
      format.html { redirect_to cadernos_url, notice: 'Caderno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caderno
      @caderno = Caderno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caderno_params
      params.require(:caderno).permit(:titulo, :conteudo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadernos_helper.rb
module CadernosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cadernos/_form.html.erb
<%= form_with(model: caderno, local: true) do |form| %>
  <% if caderno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caderno.errors.count, "error") %> prohibited this caderno from being saved:</h2>

      <ul>
      <% caderno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :caderno_titulo, heigth: 1000 %>
  </div>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.cktext_area :conteudo, id: :caderno_conteudo, cols: 40, lines: 100, ckeditor: { uiColor: '#505050', toolbar: 'full', resize_enabled: false, width: '100%', height: 500 } %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cadernos/edit.html.erb
 <h1>Editando caderno <?= @caderno $></h1>

<%= render 'form', caderno: @caderno %>

<%= link_to 'Show', @caderno %> |
<%= link_to 'Back', cadernos_path %>

app/views/cadernos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadernos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadernos.each do |caderno| %>
      <tr>
        <td><%= caderno.titulo %></td>
        <td><%= caderno.conteudo %></td>
        <td><%= link_to 'Show', caderno %></td>
        <td><%= link_to 'Edit', edit_caderno_path(caderno) %></td>
        <td><%= link_to 'Destroy', caderno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caderno', new_caderno_path %>

app/views/cadernos/new.html.erb
<h1>New Caderno</h1>

<%= render 'form', caderno: @caderno %>

<%= link_to 'Back', cadernos_path %>

app/views/cadernos/show.html.erb
<p id="notice"><%= notice %></p>
<div class = titulo>
	<h1><strong><center><%= @caderno.titulo %></center></strong></h1>
</div>
<div class = conteudo>
	<%= @caderno.conteudo.html_safe %>
</div>
<div class = menuInferior>
<center><ul>
  <li>
	<%= link_to 'Editar', edit_caderno_path(@caderno) %>
	</li>
	<li>
	<%= link_to 'Voltar', cadernos_path %>
	</li>
</ul></center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
	  <style>
		html, body {
		    margin: 0;
		    padding: 0;
		}
	  	.titulo{
	  		background: #A0A0A0;
	  		margin: auto;
			width: 100%;
			border: 1px solid gray;
			padding: 0px;
			color: #fff;
	  	}
		.conteudo {
			margin : auto;
			width: 100%;
			border: 1px solid gray;
			padding: -10px;
			background: #f0f0f0;
			color: black;
		}
		.menuInferior {
			background: #A0A0A0;
	  		margin: auto;
			width: 100%;
			border: 1px solid gray;
			padding: 0px;
			color: #fff;
		}
		.menuInferior ul {
		    list-style-type: none;
		    margin: 0;
		    padding: 0;
		    overflow: hidden;
		    background-color: #333;
		}
		.menuInferior li {
		    float: right;
		}
		.menuInferior li a {
		    display: block;
		    color: white;
		    text-align: center;
		    padding: 14px 16px;
		    text-decoration: none;
		}

	</style>
    <title>CodeBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>